# Version of the specification language/format, to manage future changes
spec_version = "1.0"
# Version of this particular benchmark suite, to manage any important changes
suite_version = "0.1"
# Unique identifier for this benchmark suite
id = "compilation_benchmarks_small"
# Human readable description
description = "Benchmarks measure compilation performance on smaller circuits"

# --------- Compilers ----------
# The set of compilers to benchmark
# For now, this is just the compiler id, but this format # could be extended to set settings for each compiler
[[compilers]]
id = "ucc"
[[compilers]]
id = "ucc+mps"

# --------- Benchmarks ----------
# Define the set of individual benchmarks
# This benchmarks add a simulation stage to calculate some observable or metric
# on the pre-post compiled circuits with and without noise to see the impact of the
# compiler on performance.
# For now, we use a common depolarizing noise model that is defined entirely in the code.
# In the future, we could expand to make the noise model, or its parameters, configurable
# as well.

[[benchmarks]]
# Unique identifier for this benchmark
id = "qaoa"
# Human readable description
description = "Quantum Approximate Optimization Algorithm of Barabási–Albert graph"
# Path to the QASM file containing the benchmark (relative to this file)
qasm_file = "circuits/benchpress/qaoa_barabasi_albert_N10_3reps_basis_rz_rx_ry_cx.qasm"


[[benchmarks]]
id = "qv"
description = "Quantum Volume"
qasm_file = "circuits/benchpress/qv_N010_12345_basis_rz_rx_ry_cx.qasm"

[[benchmarks]]
id = "qft"
description = "Quantum Fourier Transform"
qasm_file = "circuits/benchpress/qft_N010_basis_rz_rx_ry_cx.qasm"

[[benchmarks]]
id="square_heisenberg"
description = "Heisenberg spin model on square lattice"
qasm_file = "circuits/benchpress/square_heisenberg_N9_basis_rz_rx_ry_cx.qasm"

[[benchmarks]]
id="prep_select"
description = "GHZ state preparation"
qasm_file = "circuits/ucc/prep_select_N10_ghz_basis_rz_rx_ry_h_cx.qasm"

[[benchmarks]]
id="qcnn"
description="Quantum Convolutional Neural Network"
qasm_file="circuits/ucc/qcnn_N10_4layers_basis_rz_rx_ry_h_cx.qasm"
