spec_version = "1.0"
suite_version = "0.1"
id = "layout_benchmarks"
description = "Benchmarks to measure compiler layout pass performance"

# --------- Compilers ----------
# For now, restricting to qiskit derived compilers to work with the same target-device options
[[compilers]]
id = "ucc"
[[compilers]]
id = "qiskit-default"

# --------- Target Devices ----------
[[target_devices]]
id = "ibm_fake_washington"

[[target_devices]]
id = "ibm_fake_brooklyn"

# --------- Benchmarks ----------
[[benchmarks]]
id = "qaoa"
description = "Quantum Approximate Optimization Algorithm of Barabási–Albert graph"
qasm_file = "circuits/benchpress/qaoa_barabasi_albert_N10_3reps_basis_rz_rx_ry_cx.qasm"

[[benchmarks]]
id = "qv"
description = "Quantum Volume"
qasm_file = "circuits/benchpress/qv_N010_12345_basis_rz_rx_ry_cx.qasm"

[[benchmarks]]
id = "qft"
description = "Quantum Fourier Transform"
qasm_file = "circuits/benchpress/qft_N010_basis_rz_rx_ry_cx.qasm"

[[benchmarks]]
id="square_heisenberg"
description = "Heisenberg spin model on square lattice"
qasm_file = "circuits/benchpress/square_heisenberg_N9_basis_rz_rx_ry_cx.qasm"

# UCC crashing with out of bounds on this (ucc-default isn't)
# [[benchmarks]]
# id="prep_select"
# description = "GHZ state preparation"
# qasm_file = "circuits/ucc/prep_select_N10_ghz_basis_rz_rx_ry_h_cx.qasm"

[[benchmarks]]
id="qcnn"
description="Quantum Convolutional Neural Network"
qasm_file="circuits/ucc/qcnn_N10_4layers_basis_rz_rx_ry_h_cx.qasm"
