name: Plot Latest Benchmark

on:
  schedule:
    - cron: "0 */4 * * *" # Runs every 4 hours
  workflow_dispatch: # Allows manual triggering

# The runner to get results for (may be changed if we change runners)
env:
  RUNNER_LABEL: ucc-benchmarks-8-core-U22.04

jobs:
  plot-latest-benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run benchmark plot script
        run: |
          uv run python .github/scripts/plot_latest_benchmark.py results ${RUNNER_LABEL}
          uv run python .github/scripts/plot_avg_by_time_benchmark.py results ${RUNNER_LABEL}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add ./results/*
          git diff-index --quiet HEAD || git commit -m "[benchmark chore] Update benchmark plots"

      - name: Pull with rebase
        run: git pull --rebase origin ${{ github.ref_name }}

      - name: Push changes
        run: git push origin HEAD:${{ github.ref_name }}
