# Run benchmarks on pull requests and post a comment back detailing the results.
# Unlike benchmarks on pushes, these results are not committed back to the repo.
# The purpose here is to provide performance view before merging a PR.
# This will only be run if the PR has the label "preview-benchmark-results"
# and will be skipped if the label is removed.
#
# !!This workflow is triggered by PRs in the ucc-bench repo. For PRs to the UCC
# !!repo, the there is a another `run_benchmarks_pr_ucc.yml` workflow that is triggered
name: Run ucc-bench PR Benchmark Comparison

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

permissions:
  pull-requests: write
  contents: read
# Set the runner name here for use in a later step, but also next to
# the actual runs-on designation below so users know to change both together
env:
  RUNNER_LABEL: ucc-benchmarks-8-core-U22.04
jobs:
  run-ucc-benchmarks-pr:
    if: contains(github.event.pull_request.labels.*.name, 'preview-benchmark-results')
    runs-on: ucc-benchmarks-8-core-U22.04

    # Cancel if a newer commit is pushed to the PR
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true

    steps:
      # Prepare a token of Github App to post the comment
      # Note the private key needs to be PKCS#8 format, so
      # follow https://github.com/gr2m/universal-github-app-jwt?tab=readme-ov-file#converting-openssh-to-pkcs8
      # to convert to another format before adding it as a secret
      # Run this step first to fail fast
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.UCC_BENCH_APP_ID }}
          private-key: ${{ secrets.UCC_BENCH_APP_PRIVATE_KEY }}
          owner: unitaryfoundation
          repositories: ucc-bench

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to walk ancestor commits
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Run benchmarks and post PR comment
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: bash .github/scripts/run_benchmarks_pr.sh $RUNNER_LABEL ${{ github.sha }} ${{ github.event.pull_request.number }}
