# Run benchmarks on pull requests and generate a comment to post back detailing the results.
# Unlike benchmarks on pushes, these results are not committed back to the repo.
# The purpose here is to provide performance view before merging a PR.
# This will only be run if the PR has the label "preview-benchmark-results"
# and will be skipped if the label is removed.
#
# This job only runs and generates the comments. A subsequent run_benchmarks_pr_post will be
# triggered to do the post. These are separate steps because this job is running 3rd party contributed
# code, and should not have access to the secrets needed to post a PR comment.
#
# !!This workflow is triggered by PRs in the ucc-bench repo. For PRs to the UCC
# !!repo, the there is a another `run_benchmarks_pr_ucc.yml` workflow that is triggered
name: Run ucc-bench PR Benchmark Comparison

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

# Set the runner name here for use in a later step, but also next to
# the actual runs-on designation below so users know to change both together
env:
  RUNNER_LABEL: ucc-benchmarks-8-core-U22.04
jobs:
  run-ucc-benchmarks-pr:
    if: contains(github.event.pull_request.labels.*.name, 'preview-benchmark-results')
    runs-on: ucc-benchmarks-8-core-U22.04

    # Cancel if a newer commit is pushed to the PR
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to walk ancestor commits

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Run benchmarks and generate PR comment
        run: bash .github/scripts/run_benchmarks_pr.sh ucc-bench $RUNNER_LABEL ${{ github.sha }} ${{ github.event.pull_request.number }} comment.json

      - name: Save PR comment as artifact
        uses: actions/upload-artifact@v4
        with:
          name: comment.json
          path: comment.json

