# Job that automates upgrading UCC to a specific commit in the UCC repo
# This workflow enables us to benchmark performance of UCC contributions on a
# per merge basis, rather than only releases.
# It is triggered from UCC repo workflow via a repository_dispatch event.
name: Upgrade UCC version

on:
  repository_dispatch:
    types: [ucc-main-push]

  workflow_dispatch:
    inputs:
      ucc_commit_hash:
        description: 'Hash of ucc commit to upgrade to'
        required: true

permissions:
    pull-requests: write

jobs:
  upgrade-ucc:
    runs-on: ubuntu-latest
    steps:
      - name: Determine UCC commit sha
        id: get_sha
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            UCC_SHA="${{ github.event.client_payload.commit_hash }}"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            UCC_SHA="${{ github.event.inputs.ucc_commit_hash }}"
          else
            echo "Unsupported event type: ${{ github.event_name }}"
            exit 1
          fi
          SHORT_UCC_SHA="${UCC_SHA:0:7}"
          echo "UCC_SHA=$UCC_SHA" >> $GITHUB_OUTPUT
          echo "SHORT_UCC_SHA=$SHORT_UCC_SHA" >> $GITHUB_OUTPUT

      - name: Checkout ucc-bench
        uses: actions/checkout@v4
        with:
          ref: main
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --all-groups

      - name: Set up git config to be bot user
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"

      - name: Update UCC dependency
        run: |
          uv add git+https://github.com/unitaryfoundation/ucc@${{ steps.get_sha.outputs.UCC_SHA }}

      - name: Commit changes
        env:
          SHORT_UCC_SHA: ${{ steps.get_sha.outputs.SHORT_UCC_SHA }}
        run: |
          git add pyproject.toml uv.lock
          git diff-index --quiet HEAD || git commit -m "[upgrade chore] Update to unitaryfoundation/ucc@${SHORT_UCC_SHA:0:7}"

      - name: Pull with rebase
        run: |
          git pull --rebase origin main

      - name: Push changes
        run: |
          git push origin HEAD:main

